### ISSUE TITLE
Class 'Braintree_clientToken' not found

### ISSUE THREAD

**Issue by jekingohel** [mschinis/braintree#1]
Hello,

I am using this plugin for my payment system. It is working perfect in localhost but when I upload whole files to cpanel then its giving me errors.

Class 'Braintree_clientToken' not found

Please give me solutions asap.

Thank you in advanced.

**Comment by mschinis** [comment]
Sorry, I just saw this ticket :disappointed: 
Thanks for reporting this, I will look into it and fix it as soon as possible.

**Comment by mschinis** [comment]
I can't reproduce the problem, so here is a set of things you need to check in your code.
- Are you using Laravel 5, or Laravel 4.2? This package supports only 4.2 at the moment.
- If you use namespacing in your controllers, make sure you include `use \Braintree_ClientToken` at the top of your document.
- make sure you use: `Braintree_ClientToken` instead of `Braintree_clientToken`. Take note of the capital letter :)

**Comment by jekingohel** [comment]
Thanks.

I have not used use \Braintree_ClientToken on top of page.

**Comment by mschinis** [comment]
Awesome. thanks for reporting, if you have any other issues please do let me know!
